org: salinsuwu
service: api-comentario

provider:
  name: aws
  runtime: python3.12	
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::164273947020:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_comentarios
    BUCKET_NAME: ${self:service}-${sls:stage}-bucket-ingesta

functions:
  crear:
    handler: comentario.lambda_handler
    environment:
      TABLE_NAME: ${self:provider.environment.TABLE_NAME}
      BUCKET_NAME: ${self:provider.environment.BUCKET_NAME}
    events:
      - http:
          path: /comentario/crear
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaComentarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    BucketIngesta:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}